server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: ${user.home}/config-repo/
#          uri: file://c:/projects/config-repo/
          clone-on-start: false
          default-label: master # in the latest git version, the first branch name is "main" instead of "master" which was in previous versions
  security:
    user:
      name: root
      password: s3cr3t

